### ISSUE TITLE
active?

### ISSUE THREAD

**Issue by Icecrown-wow** [scith/BoxBilling_Proxmox#8]
Is this project still active? And when yes, when you will release the next update?

**Comment by scith** [comment]
Hello, as you can see the initial release was done a month ago.
I released an early alpha to kick off the project, so I'm hope others will help me on this because I lack the time and skills to develop a full version. Which is also why it is free and open source (otherwise I would have made a paid app).

However, I won't be using the plugin myself until at least December so I'm not sure I will develop it further until then.

Are you interested in using it?
Thanks

**Comment by Icecrown-wow** [comment]
yes ^^ looking for a Proxmox Extension for BoxBilling for my Hosting Provider (Not online yet. But i wan't  to open a provider when i can find a Extension for BoxBilling.)

**Comment by Icecrown-wow** [comment]
I wan't to open a Marketplace for Plugins for BoxBilling, whmcs, Hostbill, etc. Maybe when it's open you can sell your etension there ^^

**Comment by scith** [comment]
OK lets keep in touch then. Feel free to contribute to the source code
